import type { ListRole } from "@/features/lists/fixtures";
import type { Importance } from "@/domain/thing";
import { CODE_ACTIVITY_LIMITS } from "./limits";

/**
 * Code Activity domain types.
 *
 * Contract rules encoded here (contracts.md v3):
 * - Pull request state and check state are separate fields.
 * - Counts are nullable. Unknown is never zero.
 * - A feed entry is a pull request, a push, or an explicit history gap.
 * - A Thing always has an assignee; a draft starts with none chosen.
 */

export type { ListRole };

export type ChangeKind = "pull_request" | "push" | "gap";
export type PullRequestState = "draft" | "open" | "merged" | "closed";
export type CheckState = "passed" | "failing" | "pending" | "none" | "unavailable";
export type CheckRunStatus = "queued" | "in_progress" | "completed";
export type CheckRunConclusion =
  | "success"
  | "failure"
  | "neutral"
  | "cancelled"
  | "skipped"
  | "timed_out"
  | "action_required";
export type PatchState = "available" | "binary" | "omitted" | "truncated" | "empty" | "unavailable";
export type SyncStatus = "ok" | "syncing" | "partial" | "stale" | "unavailable";
export type AuthorKind = "user" | "bot" | "unknown";
export type GapReason = "sync_disabled" | "missed_unrecoverable" | "object_unavailable" | "limit_reached";
export type FileStatus = "added" | "removed" | "modified" | "renamed";

export interface ChangeAuthor {
  name: string;
  kind: AuthorKind;
}

export interface CheckRun {
  id: string;
  name: string;
  status: CheckRunStatus;
  /** Null until the run completes. */
  conclusion: CheckRunConclusion | null;
  /** Human duration such as "1m 12s". Null when unknown. */
  durationLabel: string | null;
  url: string | null;
}

export interface ChangeFile {
  path: string;
  status: FileStatus;
  additions: number | null;
  deletions: number | null;
  patchState: PatchState;
  /** Raw unified patch text. Present for available and truncated states only. Always rendered as text. */
  patch: string | null;
}

export interface HistoryGap {
  from: string;
  to: string;
  reason: GapReason;
}

export interface ActivityChange {
  id: string;
  kind: ChangeKind;
  title: string;
  /** Pull request number. Null for pushes and gaps. */
  number: number | null;
  /** Null for pushes and gaps. */
  prState: PullRequestState | null;
  author: ChangeAuthor;
  headBranch: string | null;
  baseBranch: string | null;
  headSha: string | null;
  /** ISO timestamp of the latest activity. */
  updatedAt: string;
  additions: number | null;
  deletions: number | null;
  changedFiles: number | null;
  sourceUrl: string | null;
  commitUrl: string | null;
  /** Text exactly as written on GitHub. Never generated by Katalist. Null when absent. */
  description: string | null;
  checkState: CheckState;
  /** Revision the checks ran on. Null when there are none or it is unknown. */
  checksRevision: string | null;
  /** True when checksRevision differs from headSha. Stale checks must not be shown as current. */
  checksStale: boolean;
  checks: CheckRun[];
  checksPartial: boolean;
  files: ChangeFile[];
  /** True when the provider reported more files than were listed. */
  filesPartial: boolean;
  /** Set when the file list was withheld on purpose, so the empty list is not read as "no files". */
  filesUnavailableReason?: "revision_changed" | null;
  /** Set only when kind is "gap". */
  gap: HistoryGap | null;
}

export interface Freshness {
  /** Null when never synced. */
  lastSyncedAt: string | null;
  syncStatus: SyncStatus;
}

export interface ActivityFeedData {
  repositoryFullName: string;
  freshness: Freshness;
  changes: ActivityChange[];
}

export interface AssigneeCandidate {
  actorId: string;
  name: string;
  /** Real List role only. */
  role: "owner" | "collaborator";
  isSelf: boolean;
}

export interface DraftEvidence {
  changeId: string;
  headSha: string | null;
  number: number | null;
  title: string;
  sourceUrl: string | null;
}

/** Editable draft state. Every field is the user's to change. */
export interface DraftFields {
  title: string;
  description: string;
  /** Null until the user chooses. Never defaulted. */
  assigneeActorId: string | null;
  /** ISO date (YYYY-MM-DD) or null. Never inferred from text. */
  dueDate: string | null;
  ownerImportance: Importance;
}

export interface DraftPayload extends DraftFields {
  evidence: DraftEvidence;
  aiGenerated: boolean;
  /** Set only after the user reviews a source change and confirms again. */
  acknowledgeSourceChange: boolean;
}

export type DraftFailureReason = "timeout" | "invalid_output" | "unavailable" | "consent_withdrawn" | "cancelled";
export type DraftResult =
  | { ok: true; fields: Pick<DraftFields, "title" | "description"> }
  | { ok: false; reason: DraftFailureReason };

export type ConfirmFailureReason =
  | "no_response"
  | "source_changed"
  | "not_allowed"
  | "conflict"
  | "consent_withdrawn"
  | "invalid";
export type ConfirmResult =
  | { ok: true; thingId: string; replayed: boolean }
  | { ok: false; reason: ConfirmFailureReason };

export interface DraftValidation {
  ok: boolean;
  errors: Partial<Record<"title" | "description" | "assignee" | "dueDate", string>>;
}

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

/** Mirrors the confirmation function's argument checks (contracts.md 8.3). Pure and side-effect free. */
export function validateDraft(fields: DraftFields, candidates: readonly AssigneeCandidate[]): DraftValidation {
  const errors: DraftValidation["errors"] = {};
  const title = fields.title.trim();
  if (title.length === 0) errors.title = "A Thing needs a title.";
  else if (title.length > CODE_ACTIVITY_LIMITS.titleMax) {
    errors.title = `Use ${CODE_ACTIVITY_LIMITS.titleMax} characters or fewer.`;
  }
  if (fields.description.length > CODE_ACTIVITY_LIMITS.notesMax) {
    errors.description = `Use ${CODE_ACTIVITY_LIMITS.notesMax} characters or fewer.`;
  }
  if (fields.assigneeActorId === null) {
    errors.assignee = "Choose who will own the next step. A Thing always has an assignee, and Katalist does not choose for you.";
  } else if (!candidates.some((c) => c.actorId === fields.assigneeActorId)) {
    errors.assignee = "That person can no longer be assigned from here. Choose someone else.";
  }
  if (fields.dueDate !== null) {
    const valid = ISO_DATE.test(fields.dueDate) && !Number.isNaN(Date.parse(`${fields.dueDate}T00:00:00Z`));
    if (!valid) errors.dueDate = "Enter a valid date, or leave it blank.";
  }
  return { ok: Object.keys(errors).length === 0, errors };
}

// ---------------------------------------------------------------------------
// Runtime guards. Used on any data that crosses the adapter boundary so that a
// future live adapter cannot hand the UI malformed shapes unnoticed.
// ---------------------------------------------------------------------------

const CHANGE_KINDS: readonly string[] = ["pull_request", "push", "gap"];
const PR_STATES: readonly string[] = ["draft", "open", "merged", "closed"];
const CHECK_STATES: readonly string[] = ["passed", "failing", "pending", "none", "unavailable"];
const PATCH_STATES: readonly string[] = ["available", "binary", "omitted", "truncated", "empty", "unavailable"];
const SYNC_STATUSES: readonly string[] = ["ok", "syncing", "partial", "stale", "unavailable"];

export type ParseResult<T> = { ok: true; value: T } | { ok: false; error: string };

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}
function nullableCount(v: unknown): boolean {
  return v === null || (typeof v === "number" && Number.isInteger(v) && v >= 0);
}
function nullableString(v: unknown): boolean {
  return v === null || typeof v === "string";
}

export function parseActivityChange(input: unknown): ParseResult<ActivityChange> {
  if (!isRecord(input)) return { ok: false, error: "change must be an object" };
  const c = input;
  if (typeof c.id !== "string" || c.id === "") return { ok: false, error: "id is required" };
  if (typeof c.kind !== "string" || !CHANGE_KINDS.includes(c.kind)) return { ok: false, error: "unknown kind" };
  if (typeof c.title !== "string") return { ok: false, error: "title is required" };
  if (typeof c.updatedAt !== "string" || Number.isNaN(Date.parse(c.updatedAt))) {
    return { ok: false, error: "updatedAt must be an ISO timestamp" };
  }
  if (c.prState !== null && (typeof c.prState !== "string" || !PR_STATES.includes(c.prState))) {
    return { ok: false, error: "unknown prState" };
  }
  if (c.kind === "pull_request" && c.prState === null) return { ok: false, error: "a pull request needs a prState" };
  if (c.kind !== "pull_request" && c.prState !== null) return { ok: false, error: "only a pull request has a prState" };
  for (const key of ["additions", "deletions", "changedFiles"] as const) {
    if (!nullableCount(c[key])) return { ok: false, error: `${key} must be a non-negative integer or null` };
  }
  if (typeof c.checkState !== "string" || !CHECK_STATES.includes(c.checkState)) {
    return { ok: false, error: "unknown checkState" };
  }
  if (!Array.isArray(c.checks) || !Array.isArray(c.files)) return { ok: false, error: "checks and files must be arrays" };
  if (!nullableString(c.checksRevision) || !nullableString(c.headSha) || !nullableString(c.description)) {
    return { ok: false, error: "revision and description fields must be strings or null" };
  }
  if (!isRecord(c.author) || typeof c.author.name !== "string") return { ok: false, error: "author is required" };
  for (const f of c.files) {
    if (!isRecord(f) || typeof f.path !== "string") return { ok: false, error: "file path is required" };
    if (typeof f.patchState !== "string" || !PATCH_STATES.includes(f.patchState)) {
      return { ok: false, error: "unknown patchState" };
    }
    const hasText = f.patchState === "available" || f.patchState === "truncated";
    if (hasText && typeof f.patch !== "string") return { ok: false, error: "patch text is required for this state" };
    if (!hasText && f.patch !== null) return { ok: false, error: "patch text must be null for this state" };
  }
  if (c.kind === "gap" && !isRecord(c.gap)) return { ok: false, error: "a gap needs a range" };
  if (c.kind !== "gap" && c.gap !== null) return { ok: false, error: "only a gap has a range" };
  return { ok: true, value: c as unknown as ActivityChange };
}

export function parseActivityFeed(input: unknown): ParseResult<ActivityFeedData> {
  if (!isRecord(input)) return { ok: false, error: "feed must be an object" };
  if (typeof input.repositoryFullName !== "string") return { ok: false, error: "repositoryFullName is required" };
  const fresh = input.freshness;
  if (!isRecord(fresh) || typeof fresh.syncStatus !== "string" || !SYNC_STATUSES.includes(fresh.syncStatus)) {
    return { ok: false, error: "freshness.syncStatus is invalid" };
  }
  if (!nullableString(fresh.lastSyncedAt)) return { ok: false, error: "freshness.lastSyncedAt is invalid" };
  if (!Array.isArray(input.changes)) return { ok: false, error: "changes must be an array" };
  const seen = new Set<string>();
  for (const raw of input.changes) {
    const parsed = parseActivityChange(raw);
    if (!parsed.ok) return { ok: false, error: `change: ${parsed.error}` };
    if (seen.has(parsed.value.id)) return { ok: false, error: "duplicate change id" };
    seen.add(parsed.value.id);
  }
  return { ok: true, value: input as unknown as ActivityFeedData };
}
