import type { Thing } from "@/domain/thing";

const avatarById: Record<string, string> = {
  "p-priya": "/avatars/priya.jpg",
  "p-arjun": "/avatars/arjun.jpg",
  "p-rahul": "/avatars/rahul.jpg",
  "p-sai": "/avatars/sai.jpg",
  "p-sarah": "/avatars/sarah.jpg",
  "p-mike": "/avatars/mike.jpg",
  "p-neha": "/avatars/neha.jpg",
};

const person = (id: string, name: string) => ({
  id,
  name,
  initials: name
    .split(" ")
    .map((n) => n[0])
    .join(""),
  avatarUrl: avatarById[id] ?? null,
});

const rahul = person("p-rahul", "Rahul Mehta");
const sai = person("p-sai", "Sai");
const priya = person("p-priya", "Priya Sharma");
const arjun = person("p-arjun", "Arjun Mehta");
const nithesh = person("p-nithesh", "Nithesh");
const sudheer = person("p-sudheer", "Sudheer");
const rohit = person("p-rohit", "Rohit");
const sarah = person("p-sarah", "Sarah Kapoor");
const mike = person("p-mike", "Mike Fernandes");
const neha = person("p-neha", "Neha Rao");
const workOwners = [rahul, sai, arjun, sarah, mike, neha];

const pdfBrief = {
  id: "f1",
  name: "Launch brief.pdf",
  type: "pdf" as const,
  sizeLabel: "1.8 MB",
  url: "https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf",
};
const docxCopy = {
  id: "f2",
  name: "Homepage copy.docx",
  type: "docx" as const,
  isNew: true,
};
const pngRefs = {
  id: "f3",
  name: "Release-flow.svg",
  type: "png" as const,
  url: "/demo/release-flow-preview.svg",
};
const docxNotes = {
  id: "f4",
  name: "Research notes.docx",
  type: "docx" as const,
};

function thing(partial: Partial<Thing> & Pick<Thing, "id" | "title">): Thing {
  return {
    creator: rahul,
    owner: rahul,
    assignee: priya,
    acknowledgement: "caught",
    workStatus: "not_started",
    ownerImportance: "next",
    personalPace: "now",
    dueAt: new Date().toISOString(),
    dueHasTime: false,
    context: "work",
    listId: "l1",
    listName: "Android Release",
    cancelledAt: null,
    sortedAt: null,
    caughtAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...partial,
  };
}

const today = new Date();
const at = (h: number, m = 0) => {
  const d = new Date(today);
  d.setHours(h, m, 0, 0);
  return d.toISOString();
};
const days = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  d.setHours(9, 0, 0, 0);
  return d.toISOString();
};

export const MY_ACTOR_ID = "p-priya";

export const courtFixtures: Thing[] = [
  thing({
    id: "t-brief",
    title: "Review the launch brief",
    creator: sudheer,
    owner: sudheer,
    assignee: nithesh,
    ownerImportance: "now",
    personalPace: "now",
    workStatus: "under_progress",
    dueAt: at(16, 0),
    dueHasTime: true,
    listId: "l-website",
    listName: "Website launch",
    description: "Review the launch narrative and confirm the final scope before the team review. Check the pricing section, homepage copy and onboarding sequence. Leave feedback against the relevant file so the team can follow the changes. Please confirm any remaining blockers before 4 PM.",
    files: [pdfBrief, docxCopy, pngRefs],
    attachmentCount: 3,
  }),
  thing({
    id: "t-budget",
    title: "Confirm launch budget",
    creator: rohit,
    owner: rohit,
    assignee: nithesh,
    ownerImportance: "now",
    personalPace: "now",
    workStatus: "not_started",
    dueAt: at(17, 0),
    dueHasTime: true,
    listId: "l-website",
    listName: "Website launch",
    files: [pdfBrief],
  }),
  thing({
    id: "t-proposal",
    title: "Share the updated proposal",
    creator: rohit,
    owner: rohit,
    assignee: nithesh,
    ownerImportance: "next",
    personalPace: "now",
    workStatus: "not_started",
    dueAt: days(1),
    listId: "l-client",
    listName: "Client proposal",
  }),
  thing({
    id: "t-homepage",
    title: "Approve the homepage direction",
    creator: sudheer,
    owner: sudheer,
    assignee: nithesh,
    ownerImportance: "next",
    personalPace: "next",
    workStatus: "not_started",
    dueAt: days(1),
    listId: "l-website",
    listName: "Website launch",
    files: [pngRefs, docxCopy],
    attachmentCount: 2,
  }),
  thing({
    id: "t-interviews",
    title: "Prepare customer interviews",
    creator: nithesh,
    owner: nithesh,
    assignee: nithesh,
    ownerImportance: "next",
    personalPace: "next",
    workStatus: "not_started",
    dueAt: days(1),
    listId: "l-research",
    listName: "Research",
  }),
  thing({
    id: "t-review-onboarding",
    title: "Review onboarding copy",
    creator: sudheer,
    owner: sudheer,
    assignee: nithesh,
    ownerImportance: "later",
    personalPace: "next",
    workStatus: "not_started",
    dueAt: days(2),
    listId: "l-website",
    listName: "Website launch",
  }),
  thing({
    id: "t-onboarding",
    title: "Explore the customer onboarding flow",
    creator: nithesh,
    owner: nithesh,
    assignee: nithesh,
    ownerImportance: "later",
    personalPace: "later",
    workStatus: "not_started",
    dueAt: days(11),
    listId: "l-exp",
    listName: "Product experience",
    files: [docxNotes],
    attachmentCount: 1,
  }),
  thing({
    id: "t-research",
    title: "Plan the next research round",
    creator: rohit,
    owner: rohit,
    assignee: nithesh,
    ownerImportance: "later",
    personalPace: "later",
    workStatus: "not_started",
    dueAt: days(15),
  }),
  thing({
    id: "t-brand",
    title: "Organize brand references",
    creator: nithesh,
    owner: nithesh,
    assignee: nithesh,
    ownerImportance: "later",
    personalPace: "later",
    workStatus: "not_started",
    dueAt: days(18),
  }),
  thing({
    id: "theirs-budget",
    title: "Finalize launch budget",
    creator: nithesh,
    owner: nithesh,
    assignee: rohit,
    acknowledgement: "caught",
    workStatus: "not_started",
    personalPace: null,
    ownerImportance: "now",
    dueAt: days(-1),
    attachmentCount: 2,
    files: [pdfBrief, docxCopy],
  }),
  thing({
    id: "theirs-proposal",
    title: "Review the proposal",
    creator: nithesh,
    owner: nithesh,
    assignee: sudheer,
    acknowledgement: "waiting_for_catch",
    workStatus: "not_started",
    personalPace: null,
    ownerImportance: "next",
    attachmentCount: 1,
    files: [docxNotes],
  }),
  thing({
    id: "theirs-walkthrough",
    title: "Share the product walkthrough",
    creator: nithesh,
    owner: nithesh,
    assignee: rohit,
    acknowledgement: "caught",
    workStatus: "under_progress",
    personalPace: null,
    ownerImportance: "now",
  }),
  thing({
    id: "t1",
    title: "Finalize Play Store wording",
    assignee: rahul,
    ownerImportance: "now",
    personalPace: "now",
    workStatus: "under_progress",
    dueAt: at(17, 0),
    dueHasTime: true,
    listId: "l1",
    listName: "Android Release",
  }),
  thing({
    id: "t2",
    title: "Call vendor for shoot confirmation",
    assignee: sai,
    ownerImportance: "next",
    personalPace: "now",
    workStatus: "not_started",
    dueAt: at(12, 0),
    listId: "l2",
    listName: "Mobile App Launch",
  }),
  thing({
    id: "t3",
    title: "Prepare release notes",
    assignee: rahul,
    ownerImportance: "now",
    personalPace: "now",
    workStatus: "under_progress",
    dueAt: at(16, 0),
    listId: "l1",
    listName: "Android Release",
  }),
  thing({
    id: "t4",
    title: "Review in-app update flow",
    assignee: priya,
    ownerImportance: "next",
    personalPace: "now",
    workStatus: "under_progress",
    dueAt: at(18, 0),
    listId: "l1",
    listName: "Android Release",
    description: "Walk through the staged Android update with QA. Confirm the progress prompt, background download, relaunch state, and rollback copy before the 6 PM release review.",
  }),
  thing({
    id: "t5",
    title: "Coordinate with QA on fixes",
    assignee: arjun,
    ownerImportance: "now",
    personalPace: "now",
    acknowledgement: "waiting_for_catch",
    workStatus: "not_started",
    dueAt: at(16, 0),
    dueHasTime: true,
    listId: "l2",
    listName: "Mobile App Launch",
    caughtAt: null,
  }),
  thing({
    id: "t6",
    title: "Review website launch copy",
    assignee: rahul,
    ownerImportance: "now",
    personalPace: "next",
    workStatus: "under_progress",
    dueAt: days(1),
    listId: "l3",
    listName: "Website Launch",
  }),
  thing({
    id: "t7",
    title: "Book launch photographer",
    assignee: sai,
    ownerImportance: "next",
    personalPace: "next",
    workStatus: "not_started",
    dueAt: days(5),
    listId: "l3",
    listName: "Website Launch",
  }),
  thing({
    id: "t8",
    title: "Confirm domain & hosting",
    assignee: priya,
    ownerImportance: "next",
    personalPace: "next",
    workStatus: "not_started",
    dueAt: days(6),
    listId: "l3",
    listName: "Website Launch",
  }),
  ...[
    "Approve the final release checklist",
    "Resolve the checkout analytics gap",
    "Review the support handoff notes",
    "Confirm launch-day ownership",
    "Sign off the incident response rota",
  ].map((title, i) =>
    thing({
      id: `now-more-${i}`,
      title,
      creator: workOwners[i % workOwners.length],
      owner: workOwners[i % workOwners.length],
      personalPace: "now",
      ownerImportance: i % 2 === 0 ? "now" : "next",
      workStatus: i < 2 ? "under_progress" : "not_started",
      dueAt: at(14 + i, i % 2 ? 30 : 0),
      dueHasTime: true,
      description: i === 0 ? "One final pass across release owners, dependencies, escalation paths, and customer-facing notes." : undefined,
      files: i === 0 ? [pdfBrief, docxCopy, pngRefs] : i === 1 ? [docxNotes] : undefined,
      attachmentCount: i === 0 ? 3 : i === 1 ? 1 : undefined,
    }),
  ),
  ...[
    "Publish the beta feedback summary",
    "Prepare Monday's growth review",
    "Validate subscription renewal emails",
    "Schedule the partner enablement call",
    "Tighten the onboarding success metrics",
    "Review the accessibility audit fixes",
    "Draft the October product update",
  ].map((title, i) =>
    thing({
      id: `next-more-${i}`,
      title,
      creator: workOwners[(i + 3) % workOwners.length],
      owner: workOwners[(i + 3) % workOwners.length],
      personalPace: "next",
      ownerImportance: "next",
      workStatus: i % 3 === 0 ? "under_progress" : "not_started",
      dueAt: days(1 + Math.floor(i / 2)),
      listId: i % 2 === 0 ? "l2" : "l3",
      listName: i % 2 === 0 ? "Mobile App Launch" : "Website Launch",
      files: i === 0 ? [pngRefs, pdfBrief] : undefined,
      attachmentCount: i === 0 ? 2 : undefined,
    }),
  ),
  ...[
    "Map the next quarter research themes",
    "Refresh the customer advisory board plan",
    "Consolidate legacy help-centre articles",
    "Explore a lighter approval workflow",
    "Review vendor contracts before renewal",
    "Plan the annual team offsite",
    "Revisit activation email experiments",
    "Document the design critique format",
    "Archive superseded launch assets",
    "Outline the 2027 hiring forecast",
    "Collect ideas for the mobile dashboard",
  ].map((title, i) =>
    thing({
      id: `later-${i}`,
      title,
      creator: workOwners[(i + 1) % workOwners.length],
      owner: workOwners[(i + 1) % workOwners.length],
      personalPace: "later",
      ownerImportance: "later",
      dueAt: days(7 + i * 2),
      listId: i % 2 === 0 ? "l4" : "l3",
      listName: i % 2 === 0 ? "Q4 Marketing Plan" : "Website Launch",
      files: i === 0 ? [docxNotes] : undefined,
      attachmentCount: i === 0 ? 1 : undefined,
    }),
  ),
  ...[
    "Confirm the Play Store rollout window",
    "Share the final QA evidence",
    "Approve the launch email sequence",
  ].map((title, i) =>
    thing({
      id: `theirs-wait-${i}`,
      title,
      owner: priya,
      assignee: rahul,
      acknowledgement: "waiting_for_catch",
      personalPace: null,
      ownerImportance: "now",
    }),
  ),
  ...[
    "Fix the tablet navigation regression",
    "Complete release candidate testing",
    "Prepare the customer support macros",
    "Update the partner rollout tracker",
  ].map((title, i) =>
    thing({
      id: `theirs-move-${i}`,
      title,
      owner: priya,
      assignee: sai,
      acknowledgement: "caught",
      workStatus: "under_progress",
      personalPace: "now",
    }),
  ),
  ...[
    "Resolve the blocked payment verification",
    "Confirm the legal copy changes",
  ].map((title, i) =>
    thing({
      id: `theirs-attn-${i}`,
      title,
      owner: priya,
      assignee: arjun,
      acknowledgement: "caught",
      workStatus: "not_started",
      dueAt: days(-2),
      personalPace: "now",
    }),
  ),
  // Home context: life admin shares the same Court as work.
  ...([
    { title: "Call Mom about Sunday lunch", owner: neha, pace: "now", due: at(19, 0), list: null },
    { title: "Book Goa flights for December", owner: neha, pace: "now", due: days(2), list: "l6" },
    { title: "Pick up groceries on the way home", owner: arjun, pace: "now", due: at(20, 0), list: null },
    { title: "Pick the hotel for the Goa trip", owner: arjun, pace: "next", due: days(3), list: "l6" },
    { title: "Get the painter's quote", owner: mike, pace: "next", due: days(4), list: "l7" },
    { title: "Renew the car insurance", owner: priya, pace: "next", due: days(6), list: null },
    { title: "Plan Ananya's birthday dinner", owner: neha, pace: "later", due: days(12), list: null },
    { title: "Choose kitchen lights", owner: mike, pace: "later", due: days(15), list: "l7" },
  ] as const).map(({ title, owner, pace, due, list }, i) =>
    thing({
      id: `home-${i}`,
      title,
      creator: owner,
      owner,
      assignee: priya,
      context: "home",
      personalPace: pace,
      // Owner importance stays below NOW so these never compete for the Doorman.
      ownerImportance: pace === "now" ? "next" : pace,
      workStatus: i % 3 === 0 ? "under_progress" : "not_started",
      dueAt: due,
      dueHasTime: i === 0 || i === 2,
      listId: list,
      listName: list === "l6" ? "Family Trip to Goa" : list === "l7" ? "Home Renovation" : null,
    }),
  ),
  // Recently sorted history, so the Me screen shows a real streak.
  ...[
    "Send the venue deposit",
    "Pick tiles for the bathroom",
    "Share the beta invite list",
    "Confirm the photographer",
  ].map((title, i) =>
    thing({
      id: `sorted-${i}`,
      title,
      assignee: priya,
      workStatus: "sorted",
      sortedAt: days(-i),
      context: i === 1 ? "home" : "work",
      listId: i === 1 ? "l7" : "l3",
      listName: i === 1 ? "Home Renovation" : "Website Launch",
    }),
  ),
];
