/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BucketsRouteImport } from './routes/buckets'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as MeRouteImport } from './routes/me'
import { Route as NudgesRouteImport } from './routes/nudges'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ApiPublicBridgeActRouteImport } from './routes/api/public/bridge/act'
import { Route as ApiPublicBridgeCommentRouteImport } from './routes/api/public/bridge/comment'
import { Route as ApiPublicBridgeRedeemRouteImport } from './routes/api/public/bridge/redeem'
import { Route as ApiPublicBridgeThingRouteImport } from './routes/api/public/bridge/thing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsRoute = BucketsRouteImport.update({
  id: '/buckets',
  path: '/buckets',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NudgesRoute = NudgesRouteImport.update({
  id: '/nudges',
  path: '/nudges',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeActRoute = ApiPublicBridgeActRouteImport.update({
  id: '/api/public/bridge/act',
  path: '/api/public/bridge/act',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeCommentRoute = ApiPublicBridgeCommentRouteImport.update({
  id: '/api/public/bridge/comment',
  path: '/api/public/bridge/comment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeRedeemRoute = ApiPublicBridgeRedeemRouteImport.update({
  id: '/api/public/bridge/redeem',
  path: '/api/public/bridge/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeThingRoute = ApiPublicBridgeThingRouteImport.update({
  id: '/api/public/bridge/thing',
  path: '/api/public/bridge/thing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buckets': typeof BucketsRoute
  '/lists': typeof ListsRoute
  '/me': typeof MeRoute
  '/nudges': typeof NudgesRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/bridge/act': typeof ApiPublicBridgeActRoute
  '/api/public/bridge/comment': typeof ApiPublicBridgeCommentRoute
  '/api/public/bridge/redeem': typeof ApiPublicBridgeRedeemRoute
  '/api/public/bridge/thing': typeof ApiPublicBridgeThingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buckets': typeof BucketsRoute
  '/lists': typeof ListsRoute
  '/me': typeof MeRoute
  '/nudges': typeof NudgesRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/bridge/act': typeof ApiPublicBridgeActRoute
  '/api/public/bridge/comment': typeof ApiPublicBridgeCommentRoute
  '/api/public/bridge/redeem': typeof ApiPublicBridgeRedeemRoute
  '/api/public/bridge/thing': typeof ApiPublicBridgeThingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buckets': typeof BucketsRoute
  '/lists': typeof ListsRoute
  '/me': typeof MeRoute
  '/nudges': typeof NudgesRoute
  '/welcome': typeof WelcomeRoute
  '/api/public/bridge/act': typeof ApiPublicBridgeActRoute
  '/api/public/bridge/comment': typeof ApiPublicBridgeCommentRoute
  '/api/public/bridge/redeem': typeof ApiPublicBridgeRedeemRoute
  '/api/public/bridge/thing': typeof ApiPublicBridgeThingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buckets'
    | '/lists'
    | '/me'
    | '/nudges'
    | '/welcome'
    | '/api/public/bridge/act'
    | '/api/public/bridge/comment'
    | '/api/public/bridge/redeem'
    | '/api/public/bridge/thing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buckets'
    | '/lists'
    | '/me'
    | '/nudges'
    | '/welcome'
    | '/api/public/bridge/act'
    | '/api/public/bridge/comment'
    | '/api/public/bridge/redeem'
    | '/api/public/bridge/thing'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buckets'
    | '/lists'
    | '/me'
    | '/nudges'
    | '/welcome'
    | '/api/public/bridge/act'
    | '/api/public/bridge/comment'
    | '/api/public/bridge/redeem'
    | '/api/public/bridge/thing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BucketsRoute: typeof BucketsRoute
  ListsRoute: typeof ListsRoute
  MeRoute: typeof MeRoute
  NudgesRoute: typeof NudgesRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicBridgeActRoute: typeof ApiPublicBridgeActRoute
  ApiPublicBridgeCommentRoute: typeof ApiPublicBridgeCommentRoute
  ApiPublicBridgeRedeemRoute: typeof ApiPublicBridgeRedeemRoute
  ApiPublicBridgeThingRoute: typeof ApiPublicBridgeThingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets': {
      id: '/buckets'
      path: '/buckets'
      fullPath: '/buckets'
      preLoaderRoute: typeof BucketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nudges': {
      id: '/nudges'
      path: '/nudges'
      fullPath: '/nudges'
      preLoaderRoute: typeof NudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/act': {
      id: '/api/public/bridge/act'
      path: '/api/public/bridge/act'
      fullPath: '/api/public/bridge/act'
      preLoaderRoute: typeof ApiPublicBridgeActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/comment': {
      id: '/api/public/bridge/comment'
      path: '/api/public/bridge/comment'
      fullPath: '/api/public/bridge/comment'
      preLoaderRoute: typeof ApiPublicBridgeCommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/redeem': {
      id: '/api/public/bridge/redeem'
      path: '/api/public/bridge/redeem'
      fullPath: '/api/public/bridge/redeem'
      preLoaderRoute: typeof ApiPublicBridgeRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/thing': {
      id: '/api/public/bridge/thing'
      path: '/api/public/bridge/thing'
      fullPath: '/api/public/bridge/thing'
      preLoaderRoute: typeof ApiPublicBridgeThingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BucketsRoute: BucketsRoute,
  ListsRoute: ListsRoute,
  MeRoute: MeRoute,
  NudgesRoute: NudgesRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicBridgeActRoute: ApiPublicBridgeActRoute,
  ApiPublicBridgeCommentRoute: ApiPublicBridgeCommentRoute,
  ApiPublicBridgeRedeemRoute: ApiPublicBridgeRedeemRoute,
  ApiPublicBridgeThingRoute: ApiPublicBridgeThingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
