/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BucketsRouteImport } from './routes/buckets'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as MeRouteImport } from './routes/me'
import { Route as NudgesRouteImport } from './routes/nudges'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as BridgeTokenRouteImport } from './routes/bridge.$token'
import { Route as BucketsIndexRouteImport } from './routes/buckets.index'
import { Route as BucketsBucketIdRouteImport } from './routes/buckets.$bucketId'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as ListsListIdRouteImport } from './routes/lists.$listId'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamConversationIdRouteImport } from './routes/team.$conversationId'
import { Route as ApiCallsRingRouteImport } from './routes/api/calls/ring'
import { Route as ApiCodeActivityAssigneeCandidatesRouteImport } from './routes/api/code-activity/assignee-candidates'
import { Route as ApiCodeActivityBranchesRouteImport } from './routes/api/code-activity/branches'
import { Route as ApiCodeActivityCapabilitiesRouteImport } from './routes/api/code-activity/capabilities'
import { Route as ApiCodeActivityChangeStatsRouteImport } from './routes/api/code-activity/change-stats'
import { Route as ApiCodeActivityCommitDetailRouteImport } from './routes/api/code-activity/commit-detail'
import { Route as ApiCodeActivityCommitsRouteImport } from './routes/api/code-activity/commits'
import { Route as ApiCodeActivityCompareRouteImport } from './routes/api/code-activity/compare'
import { Route as ApiCodeActivityConnectionRouteImport } from './routes/api/code-activity/connection'
import { Route as ApiCodeActivityConsentRouteImport } from './routes/api/code-activity/consent'
import { Route as ApiCodeActivityDeploymentsRouteImport } from './routes/api/code-activity/deployments'
import { Route as ApiCodeActivityFeedRouteImport } from './routes/api/code-activity/feed'
import { Route as ApiCodeActivityRefreshRouteImport } from './routes/api/code-activity/refresh'
import { Route as ApiCodeActivityWorkspaceConfirmRouteImport } from './routes/api/code-activity/workspace-confirm'
import { Route as ApiCodeActivityWorkspaceSourceRouteImport } from './routes/api/code-activity/workspace-source'
import { Route as ApiHubNotifyMessageRouteImport } from './routes/api/hub/notify-message'
import { Route as ApiJobsCodeActivityDrainRouteImport } from './routes/api/jobs/code-activity-drain'
import { Route as ApiJobsDailyMaintenanceRouteImport } from './routes/api/jobs/daily-maintenance'
import { Route as ApiJobsEscalateNudgesRouteImport } from './routes/api/jobs/escalate-nudges'
import { Route as ApiNudgesNotifyRouteImport } from './routes/api/nudges/notify'
import { Route as ApiPushTestRouteImport } from './routes/api/push/test'
import { Route as ApiThingsNotifyMentionRouteImport } from './routes/api/things/notify-mention'
import { Route as ApiCodeActivityChangesDetailRouteImport } from './routes/api/code-activity/changes/detail'
import { Route as ApiCodeActivityChangesDraftRouteImport } from './routes/api/code-activity/changes/draft'
import { Route as ApiCodeActivityChangesSummaryRouteImport } from './routes/api/code-activity/changes/summary'
import { Route as ApiCodeActivityDraftsConfirmRouteImport } from './routes/api/code-activity/drafts/confirm'
import { Route as ApiCodeActivityGithubRepositoriesRouteImport } from './routes/api/code-activity/github/repositories'
import { Route as ApiPublicBridgeActRouteImport } from './routes/api/public/bridge/act'
import { Route as ApiPublicBridgeCommentRouteImport } from './routes/api/public/bridge/comment'
import { Route as ApiPublicBridgeRedeemRouteImport } from './routes/api/public/bridge/redeem'
import { Route as ApiPublicBridgeThingRouteImport } from './routes/api/public/bridge/thing'
import { Route as ApiCodeActivityGithubAuthorizeCallbackRouteImport } from './routes/api/code-activity/github/authorize/callback'
import { Route as ApiCodeActivityGithubAuthorizeStartRouteImport } from './routes/api/code-activity/github/authorize/start'
import { Route as ApiPublicCodeActivityGithubWebhookRouteImport } from './routes/api/public/code-activity/github/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsRoute = BucketsRouteImport.update({
  id: '/buckets',
  path: '/buckets',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NudgesRoute = NudgesRouteImport.update({
  id: '/nudges',
  path: '/nudges',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeTokenRoute = BridgeTokenRouteImport.update({
  id: '/bridge/$token',
  path: '/bridge/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsIndexRoute = BucketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BucketsRoute,
} as any)
const BucketsBucketIdRoute = BucketsBucketIdRouteImport.update({
  id: '/$bucketId',
  path: '/$bucketId',
  getParentRoute: () => BucketsRoute,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListsRoute,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => ListsRoute,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamConversationIdRoute = TeamConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => TeamRoute,
} as any)
const ApiCallsRingRoute = ApiCallsRingRouteImport.update({
  id: '/api/calls/ring',
  path: '/api/calls/ring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeActivityAssigneeCandidatesRoute =
  ApiCodeActivityAssigneeCandidatesRouteImport.update({
    id: '/api/code-activity/assignee-candidates',
    path: '/api/code-activity/assignee-candidates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityBranchesRoute = ApiCodeActivityBranchesRouteImport.update({
  id: '/api/code-activity/branches',
  path: '/api/code-activity/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeActivityCapabilitiesRoute =
  ApiCodeActivityCapabilitiesRouteImport.update({
    id: '/api/code-activity/capabilities',
    path: '/api/code-activity/capabilities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityChangeStatsRoute =
  ApiCodeActivityChangeStatsRouteImport.update({
    id: '/api/code-activity/change-stats',
    path: '/api/code-activity/change-stats',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityCommitDetailRoute =
  ApiCodeActivityCommitDetailRouteImport.update({
    id: '/api/code-activity/commit-detail',
    path: '/api/code-activity/commit-detail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityCommitsRoute = ApiCodeActivityCommitsRouteImport.update({
  id: '/api/code-activity/commits',
  path: '/api/code-activity/commits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeActivityCompareRoute = ApiCodeActivityCompareRouteImport.update({
  id: '/api/code-activity/compare',
  path: '/api/code-activity/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeActivityConnectionRoute =
  ApiCodeActivityConnectionRouteImport.update({
    id: '/api/code-activity/connection',
    path: '/api/code-activity/connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityConsentRoute = ApiCodeActivityConsentRouteImport.update({
  id: '/api/code-activity/consent',
  path: '/api/code-activity/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeActivityDeploymentsRoute =
  ApiCodeActivityDeploymentsRouteImport.update({
    id: '/api/code-activity/deployments',
    path: '/api/code-activity/deployments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityFeedRoute = ApiCodeActivityFeedRouteImport.update({
  id: '/api/code-activity/feed',
  path: '/api/code-activity/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeActivityRefreshRoute = ApiCodeActivityRefreshRouteImport.update({
  id: '/api/code-activity/refresh',
  path: '/api/code-activity/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeActivityWorkspaceConfirmRoute =
  ApiCodeActivityWorkspaceConfirmRouteImport.update({
    id: '/api/code-activity/workspace-confirm',
    path: '/api/code-activity/workspace-confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityWorkspaceSourceRoute =
  ApiCodeActivityWorkspaceSourceRouteImport.update({
    id: '/api/code-activity/workspace-source',
    path: '/api/code-activity/workspace-source',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHubNotifyMessageRoute = ApiHubNotifyMessageRouteImport.update({
  id: '/api/hub/notify-message',
  path: '/api/hub/notify-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsCodeActivityDrainRoute =
  ApiJobsCodeActivityDrainRouteImport.update({
    id: '/api/jobs/code-activity-drain',
    path: '/api/jobs/code-activity-drain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiJobsDailyMaintenanceRoute = ApiJobsDailyMaintenanceRouteImport.update({
  id: '/api/jobs/daily-maintenance',
  path: '/api/jobs/daily-maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsEscalateNudgesRoute = ApiJobsEscalateNudgesRouteImport.update({
  id: '/api/jobs/escalate-nudges',
  path: '/api/jobs/escalate-nudges',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNudgesNotifyRoute = ApiNudgesNotifyRouteImport.update({
  id: '/api/nudges/notify',
  path: '/api/nudges/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushTestRoute = ApiPushTestRouteImport.update({
  id: '/api/push/test',
  path: '/api/push/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThingsNotifyMentionRoute = ApiThingsNotifyMentionRouteImport.update({
  id: '/api/things/notify-mention',
  path: '/api/things/notify-mention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeActivityChangesDetailRoute =
  ApiCodeActivityChangesDetailRouteImport.update({
    id: '/api/code-activity/changes/detail',
    path: '/api/code-activity/changes/detail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityChangesDraftRoute =
  ApiCodeActivityChangesDraftRouteImport.update({
    id: '/api/code-activity/changes/draft',
    path: '/api/code-activity/changes/draft',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityChangesSummaryRoute =
  ApiCodeActivityChangesSummaryRouteImport.update({
    id: '/api/code-activity/changes/summary',
    path: '/api/code-activity/changes/summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityDraftsConfirmRoute =
  ApiCodeActivityDraftsConfirmRouteImport.update({
    id: '/api/code-activity/drafts/confirm',
    path: '/api/code-activity/drafts/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityGithubRepositoriesRoute =
  ApiCodeActivityGithubRepositoriesRouteImport.update({
    id: '/api/code-activity/github/repositories',
    path: '/api/code-activity/github/repositories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeActRoute = ApiPublicBridgeActRouteImport.update({
  id: '/api/public/bridge/act',
  path: '/api/public/bridge/act',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeCommentRoute = ApiPublicBridgeCommentRouteImport.update({
  id: '/api/public/bridge/comment',
  path: '/api/public/bridge/comment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeRedeemRoute = ApiPublicBridgeRedeemRouteImport.update({
  id: '/api/public/bridge/redeem',
  path: '/api/public/bridge/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeThingRoute = ApiPublicBridgeThingRouteImport.update({
  id: '/api/public/bridge/thing',
  path: '/api/public/bridge/thing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeActivityGithubAuthorizeCallbackRoute =
  ApiCodeActivityGithubAuthorizeCallbackRouteImport.update({
    id: '/api/code-activity/github/authorize/callback',
    path: '/api/code-activity/github/authorize/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCodeActivityGithubAuthorizeStartRoute =
  ApiCodeActivityGithubAuthorizeStartRouteImport.update({
    id: '/api/code-activity/github/authorize/start',
    path: '/api/code-activity/github/authorize/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCodeActivityGithubWebhookRoute =
  ApiPublicCodeActivityGithubWebhookRouteImport.update({
    id: '/api/public/code-activity/github/webhook',
    path: '/api/public/code-activity/github/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buckets': typeof BucketsRouteWithChildren
  '/lists': typeof ListsRouteWithChildren
  '/me': typeof MeRoute
  '/nudges': typeof NudgesRoute
  '/onboarding': typeof OnboardingRoute
  '/team': typeof TeamRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/bridge/$token': typeof BridgeTokenRoute
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/team/$conversationId': typeof TeamConversationIdRoute
  '/buckets/': typeof BucketsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/api/calls/ring': typeof ApiCallsRingRoute
  '/api/code-activity/assignee-candidates': typeof ApiCodeActivityAssigneeCandidatesRoute
  '/api/code-activity/branches': typeof ApiCodeActivityBranchesRoute
  '/api/code-activity/capabilities': typeof ApiCodeActivityCapabilitiesRoute
  '/api/code-activity/change-stats': typeof ApiCodeActivityChangeStatsRoute
  '/api/code-activity/commit-detail': typeof ApiCodeActivityCommitDetailRoute
  '/api/code-activity/commits': typeof ApiCodeActivityCommitsRoute
  '/api/code-activity/compare': typeof ApiCodeActivityCompareRoute
  '/api/code-activity/connection': typeof ApiCodeActivityConnectionRoute
  '/api/code-activity/consent': typeof ApiCodeActivityConsentRoute
  '/api/code-activity/deployments': typeof ApiCodeActivityDeploymentsRoute
  '/api/code-activity/feed': typeof ApiCodeActivityFeedRoute
  '/api/code-activity/refresh': typeof ApiCodeActivityRefreshRoute
  '/api/code-activity/workspace-confirm': typeof ApiCodeActivityWorkspaceConfirmRoute
  '/api/code-activity/workspace-source': typeof ApiCodeActivityWorkspaceSourceRoute
  '/api/hub/notify-message': typeof ApiHubNotifyMessageRoute
  '/api/jobs/code-activity-drain': typeof ApiJobsCodeActivityDrainRoute
  '/api/jobs/daily-maintenance': typeof ApiJobsDailyMaintenanceRoute
  '/api/jobs/escalate-nudges': typeof ApiJobsEscalateNudgesRoute
  '/api/nudges/notify': typeof ApiNudgesNotifyRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/things/notify-mention': typeof ApiThingsNotifyMentionRoute
  '/api/code-activity/changes/detail': typeof ApiCodeActivityChangesDetailRoute
  '/api/code-activity/changes/draft': typeof ApiCodeActivityChangesDraftRoute
  '/api/code-activity/changes/summary': typeof ApiCodeActivityChangesSummaryRoute
  '/api/code-activity/drafts/confirm': typeof ApiCodeActivityDraftsConfirmRoute
  '/api/code-activity/github/repositories': typeof ApiCodeActivityGithubRepositoriesRoute
  '/api/public/bridge/act': typeof ApiPublicBridgeActRoute
  '/api/public/bridge/comment': typeof ApiPublicBridgeCommentRoute
  '/api/public/bridge/redeem': typeof ApiPublicBridgeRedeemRoute
  '/api/public/bridge/thing': typeof ApiPublicBridgeThingRoute
  '/api/code-activity/github/authorize/callback': typeof ApiCodeActivityGithubAuthorizeCallbackRoute
  '/api/code-activity/github/authorize/start': typeof ApiCodeActivityGithubAuthorizeStartRoute
  '/api/public/code-activity/github/webhook': typeof ApiPublicCodeActivityGithubWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/nudges': typeof NudgesRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/bridge/$token': typeof BridgeTokenRoute
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/team/$conversationId': typeof TeamConversationIdRoute
  '/buckets': typeof BucketsIndexRoute
  '/lists': typeof ListsIndexRoute
  '/team': typeof TeamIndexRoute
  '/api/calls/ring': typeof ApiCallsRingRoute
  '/api/code-activity/assignee-candidates': typeof ApiCodeActivityAssigneeCandidatesRoute
  '/api/code-activity/branches': typeof ApiCodeActivityBranchesRoute
  '/api/code-activity/capabilities': typeof ApiCodeActivityCapabilitiesRoute
  '/api/code-activity/change-stats': typeof ApiCodeActivityChangeStatsRoute
  '/api/code-activity/commit-detail': typeof ApiCodeActivityCommitDetailRoute
  '/api/code-activity/commits': typeof ApiCodeActivityCommitsRoute
  '/api/code-activity/compare': typeof ApiCodeActivityCompareRoute
  '/api/code-activity/connection': typeof ApiCodeActivityConnectionRoute
  '/api/code-activity/consent': typeof ApiCodeActivityConsentRoute
  '/api/code-activity/deployments': typeof ApiCodeActivityDeploymentsRoute
  '/api/code-activity/feed': typeof ApiCodeActivityFeedRoute
  '/api/code-activity/refresh': typeof ApiCodeActivityRefreshRoute
  '/api/code-activity/workspace-confirm': typeof ApiCodeActivityWorkspaceConfirmRoute
  '/api/code-activity/workspace-source': typeof ApiCodeActivityWorkspaceSourceRoute
  '/api/hub/notify-message': typeof ApiHubNotifyMessageRoute
  '/api/jobs/code-activity-drain': typeof ApiJobsCodeActivityDrainRoute
  '/api/jobs/daily-maintenance': typeof ApiJobsDailyMaintenanceRoute
  '/api/jobs/escalate-nudges': typeof ApiJobsEscalateNudgesRoute
  '/api/nudges/notify': typeof ApiNudgesNotifyRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/things/notify-mention': typeof ApiThingsNotifyMentionRoute
  '/api/code-activity/changes/detail': typeof ApiCodeActivityChangesDetailRoute
  '/api/code-activity/changes/draft': typeof ApiCodeActivityChangesDraftRoute
  '/api/code-activity/changes/summary': typeof ApiCodeActivityChangesSummaryRoute
  '/api/code-activity/drafts/confirm': typeof ApiCodeActivityDraftsConfirmRoute
  '/api/code-activity/github/repositories': typeof ApiCodeActivityGithubRepositoriesRoute
  '/api/public/bridge/act': typeof ApiPublicBridgeActRoute
  '/api/public/bridge/comment': typeof ApiPublicBridgeCommentRoute
  '/api/public/bridge/redeem': typeof ApiPublicBridgeRedeemRoute
  '/api/public/bridge/thing': typeof ApiPublicBridgeThingRoute
  '/api/code-activity/github/authorize/callback': typeof ApiCodeActivityGithubAuthorizeCallbackRoute
  '/api/code-activity/github/authorize/start': typeof ApiCodeActivityGithubAuthorizeStartRoute
  '/api/public/code-activity/github/webhook': typeof ApiPublicCodeActivityGithubWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buckets': typeof BucketsRouteWithChildren
  '/lists': typeof ListsRouteWithChildren
  '/me': typeof MeRoute
  '/nudges': typeof NudgesRoute
  '/onboarding': typeof OnboardingRoute
  '/team': typeof TeamRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/bridge/$token': typeof BridgeTokenRoute
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/team/$conversationId': typeof TeamConversationIdRoute
  '/buckets/': typeof BucketsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/api/calls/ring': typeof ApiCallsRingRoute
  '/api/code-activity/assignee-candidates': typeof ApiCodeActivityAssigneeCandidatesRoute
  '/api/code-activity/branches': typeof ApiCodeActivityBranchesRoute
  '/api/code-activity/capabilities': typeof ApiCodeActivityCapabilitiesRoute
  '/api/code-activity/change-stats': typeof ApiCodeActivityChangeStatsRoute
  '/api/code-activity/commit-detail': typeof ApiCodeActivityCommitDetailRoute
  '/api/code-activity/commits': typeof ApiCodeActivityCommitsRoute
  '/api/code-activity/compare': typeof ApiCodeActivityCompareRoute
  '/api/code-activity/connection': typeof ApiCodeActivityConnectionRoute
  '/api/code-activity/consent': typeof ApiCodeActivityConsentRoute
  '/api/code-activity/deployments': typeof ApiCodeActivityDeploymentsRoute
  '/api/code-activity/feed': typeof ApiCodeActivityFeedRoute
  '/api/code-activity/refresh': typeof ApiCodeActivityRefreshRoute
  '/api/code-activity/workspace-confirm': typeof ApiCodeActivityWorkspaceConfirmRoute
  '/api/code-activity/workspace-source': typeof ApiCodeActivityWorkspaceSourceRoute
  '/api/hub/notify-message': typeof ApiHubNotifyMessageRoute
  '/api/jobs/code-activity-drain': typeof ApiJobsCodeActivityDrainRoute
  '/api/jobs/daily-maintenance': typeof ApiJobsDailyMaintenanceRoute
  '/api/jobs/escalate-nudges': typeof ApiJobsEscalateNudgesRoute
  '/api/nudges/notify': typeof ApiNudgesNotifyRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/things/notify-mention': typeof ApiThingsNotifyMentionRoute
  '/api/code-activity/changes/detail': typeof ApiCodeActivityChangesDetailRoute
  '/api/code-activity/changes/draft': typeof ApiCodeActivityChangesDraftRoute
  '/api/code-activity/changes/summary': typeof ApiCodeActivityChangesSummaryRoute
  '/api/code-activity/drafts/confirm': typeof ApiCodeActivityDraftsConfirmRoute
  '/api/code-activity/github/repositories': typeof ApiCodeActivityGithubRepositoriesRoute
  '/api/public/bridge/act': typeof ApiPublicBridgeActRoute
  '/api/public/bridge/comment': typeof ApiPublicBridgeCommentRoute
  '/api/public/bridge/redeem': typeof ApiPublicBridgeRedeemRoute
  '/api/public/bridge/thing': typeof ApiPublicBridgeThingRoute
  '/api/code-activity/github/authorize/callback': typeof ApiCodeActivityGithubAuthorizeCallbackRoute
  '/api/code-activity/github/authorize/start': typeof ApiCodeActivityGithubAuthorizeStartRoute
  '/api/public/code-activity/github/webhook': typeof ApiPublicCodeActivityGithubWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buckets'
    | '/lists'
    | '/me'
    | '/nudges'
    | '/onboarding'
    | '/team'
    | '/welcome'
    | '/bridge/$token'
    | '/buckets/$bucketId'
    | '/lists/$listId'
    | '/team/$conversationId'
    | '/buckets/'
    | '/lists/'
    | '/team/'
    | '/api/calls/ring'
    | '/api/code-activity/assignee-candidates'
    | '/api/code-activity/branches'
    | '/api/code-activity/capabilities'
    | '/api/code-activity/change-stats'
    | '/api/code-activity/commit-detail'
    | '/api/code-activity/commits'
    | '/api/code-activity/compare'
    | '/api/code-activity/connection'
    | '/api/code-activity/consent'
    | '/api/code-activity/deployments'
    | '/api/code-activity/feed'
    | '/api/code-activity/refresh'
    | '/api/code-activity/workspace-confirm'
    | '/api/code-activity/workspace-source'
    | '/api/hub/notify-message'
    | '/api/jobs/code-activity-drain'
    | '/api/jobs/daily-maintenance'
    | '/api/jobs/escalate-nudges'
    | '/api/nudges/notify'
    | '/api/push/test'
    | '/api/things/notify-mention'
    | '/api/code-activity/changes/detail'
    | '/api/code-activity/changes/draft'
    | '/api/code-activity/changes/summary'
    | '/api/code-activity/drafts/confirm'
    | '/api/code-activity/github/repositories'
    | '/api/public/bridge/act'
    | '/api/public/bridge/comment'
    | '/api/public/bridge/redeem'
    | '/api/public/bridge/thing'
    | '/api/code-activity/github/authorize/callback'
    | '/api/code-activity/github/authorize/start'
    | '/api/public/code-activity/github/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/me'
    | '/nudges'
    | '/onboarding'
    | '/welcome'
    | '/bridge/$token'
    | '/buckets/$bucketId'
    | '/lists/$listId'
    | '/team/$conversationId'
    | '/buckets'
    | '/lists'
    | '/team'
    | '/api/calls/ring'
    | '/api/code-activity/assignee-candidates'
    | '/api/code-activity/branches'
    | '/api/code-activity/capabilities'
    | '/api/code-activity/change-stats'
    | '/api/code-activity/commit-detail'
    | '/api/code-activity/commits'
    | '/api/code-activity/compare'
    | '/api/code-activity/connection'
    | '/api/code-activity/consent'
    | '/api/code-activity/deployments'
    | '/api/code-activity/feed'
    | '/api/code-activity/refresh'
    | '/api/code-activity/workspace-confirm'
    | '/api/code-activity/workspace-source'
    | '/api/hub/notify-message'
    | '/api/jobs/code-activity-drain'
    | '/api/jobs/daily-maintenance'
    | '/api/jobs/escalate-nudges'
    | '/api/nudges/notify'
    | '/api/push/test'
    | '/api/things/notify-mention'
    | '/api/code-activity/changes/detail'
    | '/api/code-activity/changes/draft'
    | '/api/code-activity/changes/summary'
    | '/api/code-activity/drafts/confirm'
    | '/api/code-activity/github/repositories'
    | '/api/public/bridge/act'
    | '/api/public/bridge/comment'
    | '/api/public/bridge/redeem'
    | '/api/public/bridge/thing'
    | '/api/code-activity/github/authorize/callback'
    | '/api/code-activity/github/authorize/start'
    | '/api/public/code-activity/github/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buckets'
    | '/lists'
    | '/me'
    | '/nudges'
    | '/onboarding'
    | '/team'
    | '/welcome'
    | '/bridge/$token'
    | '/buckets/$bucketId'
    | '/lists/$listId'
    | '/team/$conversationId'
    | '/buckets/'
    | '/lists/'
    | '/team/'
    | '/api/calls/ring'
    | '/api/code-activity/assignee-candidates'
    | '/api/code-activity/branches'
    | '/api/code-activity/capabilities'
    | '/api/code-activity/change-stats'
    | '/api/code-activity/commit-detail'
    | '/api/code-activity/commits'
    | '/api/code-activity/compare'
    | '/api/code-activity/connection'
    | '/api/code-activity/consent'
    | '/api/code-activity/deployments'
    | '/api/code-activity/feed'
    | '/api/code-activity/refresh'
    | '/api/code-activity/workspace-confirm'
    | '/api/code-activity/workspace-source'
    | '/api/hub/notify-message'
    | '/api/jobs/code-activity-drain'
    | '/api/jobs/daily-maintenance'
    | '/api/jobs/escalate-nudges'
    | '/api/nudges/notify'
    | '/api/push/test'
    | '/api/things/notify-mention'
    | '/api/code-activity/changes/detail'
    | '/api/code-activity/changes/draft'
    | '/api/code-activity/changes/summary'
    | '/api/code-activity/drafts/confirm'
    | '/api/code-activity/github/repositories'
    | '/api/public/bridge/act'
    | '/api/public/bridge/comment'
    | '/api/public/bridge/redeem'
    | '/api/public/bridge/thing'
    | '/api/code-activity/github/authorize/callback'
    | '/api/code-activity/github/authorize/start'
    | '/api/public/code-activity/github/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BucketsRoute: typeof BucketsRouteWithChildren
  ListsRoute: typeof ListsRouteWithChildren
  MeRoute: typeof MeRoute
  NudgesRoute: typeof NudgesRoute
  OnboardingRoute: typeof OnboardingRoute
  TeamRoute: typeof TeamRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  BridgeTokenRoute: typeof BridgeTokenRoute
  ApiCallsRingRoute: typeof ApiCallsRingRoute
  ApiCodeActivityAssigneeCandidatesRoute: typeof ApiCodeActivityAssigneeCandidatesRoute
  ApiCodeActivityBranchesRoute: typeof ApiCodeActivityBranchesRoute
  ApiCodeActivityCapabilitiesRoute: typeof ApiCodeActivityCapabilitiesRoute
  ApiCodeActivityChangeStatsRoute: typeof ApiCodeActivityChangeStatsRoute
  ApiCodeActivityCommitDetailRoute: typeof ApiCodeActivityCommitDetailRoute
  ApiCodeActivityCommitsRoute: typeof ApiCodeActivityCommitsRoute
  ApiCodeActivityCompareRoute: typeof ApiCodeActivityCompareRoute
  ApiCodeActivityConnectionRoute: typeof ApiCodeActivityConnectionRoute
  ApiCodeActivityConsentRoute: typeof ApiCodeActivityConsentRoute
  ApiCodeActivityDeploymentsRoute: typeof ApiCodeActivityDeploymentsRoute
  ApiCodeActivityFeedRoute: typeof ApiCodeActivityFeedRoute
  ApiCodeActivityRefreshRoute: typeof ApiCodeActivityRefreshRoute
  ApiCodeActivityWorkspaceConfirmRoute: typeof ApiCodeActivityWorkspaceConfirmRoute
  ApiCodeActivityWorkspaceSourceRoute: typeof ApiCodeActivityWorkspaceSourceRoute
  ApiHubNotifyMessageRoute: typeof ApiHubNotifyMessageRoute
  ApiJobsCodeActivityDrainRoute: typeof ApiJobsCodeActivityDrainRoute
  ApiJobsDailyMaintenanceRoute: typeof ApiJobsDailyMaintenanceRoute
  ApiJobsEscalateNudgesRoute: typeof ApiJobsEscalateNudgesRoute
  ApiNudgesNotifyRoute: typeof ApiNudgesNotifyRoute
  ApiPushTestRoute: typeof ApiPushTestRoute
  ApiThingsNotifyMentionRoute: typeof ApiThingsNotifyMentionRoute
  ApiCodeActivityChangesDetailRoute: typeof ApiCodeActivityChangesDetailRoute
  ApiCodeActivityChangesDraftRoute: typeof ApiCodeActivityChangesDraftRoute
  ApiCodeActivityChangesSummaryRoute: typeof ApiCodeActivityChangesSummaryRoute
  ApiCodeActivityDraftsConfirmRoute: typeof ApiCodeActivityDraftsConfirmRoute
  ApiCodeActivityGithubRepositoriesRoute: typeof ApiCodeActivityGithubRepositoriesRoute
  ApiPublicBridgeActRoute: typeof ApiPublicBridgeActRoute
  ApiPublicBridgeCommentRoute: typeof ApiPublicBridgeCommentRoute
  ApiPublicBridgeRedeemRoute: typeof ApiPublicBridgeRedeemRoute
  ApiPublicBridgeThingRoute: typeof ApiPublicBridgeThingRoute
  ApiCodeActivityGithubAuthorizeCallbackRoute: typeof ApiCodeActivityGithubAuthorizeCallbackRoute
  ApiCodeActivityGithubAuthorizeStartRoute: typeof ApiCodeActivityGithubAuthorizeStartRoute
  ApiPublicCodeActivityGithubWebhookRoute: typeof ApiPublicCodeActivityGithubWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets': {
      id: '/buckets'
      path: '/buckets'
      fullPath: '/buckets'
      preLoaderRoute: typeof BucketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nudges': {
      id: '/nudges'
      path: '/nudges'
      fullPath: '/nudges'
      preLoaderRoute: typeof NudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge/$token': {
      id: '/bridge/$token'
      path: '/bridge/$token'
      fullPath: '/bridge/$token'
      preLoaderRoute: typeof BridgeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/': {
      id: '/buckets/'
      path: '/'
      fullPath: '/buckets/'
      preLoaderRoute: typeof BucketsIndexRouteImport
      parentRoute: typeof BucketsRoute
    }
    '/buckets/$bucketId': {
      id: '/buckets/$bucketId'
      path: '/$bucketId'
      fullPath: '/buckets/$bucketId'
      preLoaderRoute: typeof BucketsBucketIdRouteImport
      parentRoute: typeof BucketsRoute
    }
    '/lists/': {
      id: '/lists/'
      path: '/'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof ListsRoute
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof ListsRoute
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/$conversationId': {
      id: '/team/$conversationId'
      path: '/$conversationId'
      fullPath: '/team/$conversationId'
      preLoaderRoute: typeof TeamConversationIdRouteImport
      parentRoute: typeof TeamRoute
    }
    '/api/calls/ring': {
      id: '/api/calls/ring'
      path: '/api/calls/ring'
      fullPath: '/api/calls/ring'
      preLoaderRoute: typeof ApiCallsRingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/assignee-candidates': {
      id: '/api/code-activity/assignee-candidates'
      path: '/api/code-activity/assignee-candidates'
      fullPath: '/api/code-activity/assignee-candidates'
      preLoaderRoute: typeof ApiCodeActivityAssigneeCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/branches': {
      id: '/api/code-activity/branches'
      path: '/api/code-activity/branches'
      fullPath: '/api/code-activity/branches'
      preLoaderRoute: typeof ApiCodeActivityBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/capabilities': {
      id: '/api/code-activity/capabilities'
      path: '/api/code-activity/capabilities'
      fullPath: '/api/code-activity/capabilities'
      preLoaderRoute: typeof ApiCodeActivityCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/change-stats': {
      id: '/api/code-activity/change-stats'
      path: '/api/code-activity/change-stats'
      fullPath: '/api/code-activity/change-stats'
      preLoaderRoute: typeof ApiCodeActivityChangeStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/commit-detail': {
      id: '/api/code-activity/commit-detail'
      path: '/api/code-activity/commit-detail'
      fullPath: '/api/code-activity/commit-detail'
      preLoaderRoute: typeof ApiCodeActivityCommitDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/commits': {
      id: '/api/code-activity/commits'
      path: '/api/code-activity/commits'
      fullPath: '/api/code-activity/commits'
      preLoaderRoute: typeof ApiCodeActivityCommitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/compare': {
      id: '/api/code-activity/compare'
      path: '/api/code-activity/compare'
      fullPath: '/api/code-activity/compare'
      preLoaderRoute: typeof ApiCodeActivityCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/connection': {
      id: '/api/code-activity/connection'
      path: '/api/code-activity/connection'
      fullPath: '/api/code-activity/connection'
      preLoaderRoute: typeof ApiCodeActivityConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/consent': {
      id: '/api/code-activity/consent'
      path: '/api/code-activity/consent'
      fullPath: '/api/code-activity/consent'
      preLoaderRoute: typeof ApiCodeActivityConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/deployments': {
      id: '/api/code-activity/deployments'
      path: '/api/code-activity/deployments'
      fullPath: '/api/code-activity/deployments'
      preLoaderRoute: typeof ApiCodeActivityDeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/feed': {
      id: '/api/code-activity/feed'
      path: '/api/code-activity/feed'
      fullPath: '/api/code-activity/feed'
      preLoaderRoute: typeof ApiCodeActivityFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/refresh': {
      id: '/api/code-activity/refresh'
      path: '/api/code-activity/refresh'
      fullPath: '/api/code-activity/refresh'
      preLoaderRoute: typeof ApiCodeActivityRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/workspace-confirm': {
      id: '/api/code-activity/workspace-confirm'
      path: '/api/code-activity/workspace-confirm'
      fullPath: '/api/code-activity/workspace-confirm'
      preLoaderRoute: typeof ApiCodeActivityWorkspaceConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/workspace-source': {
      id: '/api/code-activity/workspace-source'
      path: '/api/code-activity/workspace-source'
      fullPath: '/api/code-activity/workspace-source'
      preLoaderRoute: typeof ApiCodeActivityWorkspaceSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hub/notify-message': {
      id: '/api/hub/notify-message'
      path: '/api/hub/notify-message'
      fullPath: '/api/hub/notify-message'
      preLoaderRoute: typeof ApiHubNotifyMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/code-activity-drain': {
      id: '/api/jobs/code-activity-drain'
      path: '/api/jobs/code-activity-drain'
      fullPath: '/api/jobs/code-activity-drain'
      preLoaderRoute: typeof ApiJobsCodeActivityDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/daily-maintenance': {
      id: '/api/jobs/daily-maintenance'
      path: '/api/jobs/daily-maintenance'
      fullPath: '/api/jobs/daily-maintenance'
      preLoaderRoute: typeof ApiJobsDailyMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/escalate-nudges': {
      id: '/api/jobs/escalate-nudges'
      path: '/api/jobs/escalate-nudges'
      fullPath: '/api/jobs/escalate-nudges'
      preLoaderRoute: typeof ApiJobsEscalateNudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nudges/notify': {
      id: '/api/nudges/notify'
      path: '/api/nudges/notify'
      fullPath: '/api/nudges/notify'
      preLoaderRoute: typeof ApiNudgesNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/test': {
      id: '/api/push/test'
      path: '/api/push/test'
      fullPath: '/api/push/test'
      preLoaderRoute: typeof ApiPushTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/things/notify-mention': {
      id: '/api/things/notify-mention'
      path: '/api/things/notify-mention'
      fullPath: '/api/things/notify-mention'
      preLoaderRoute: typeof ApiThingsNotifyMentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/changes/detail': {
      id: '/api/code-activity/changes/detail'
      path: '/api/code-activity/changes/detail'
      fullPath: '/api/code-activity/changes/detail'
      preLoaderRoute: typeof ApiCodeActivityChangesDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/changes/draft': {
      id: '/api/code-activity/changes/draft'
      path: '/api/code-activity/changes/draft'
      fullPath: '/api/code-activity/changes/draft'
      preLoaderRoute: typeof ApiCodeActivityChangesDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/changes/summary': {
      id: '/api/code-activity/changes/summary'
      path: '/api/code-activity/changes/summary'
      fullPath: '/api/code-activity/changes/summary'
      preLoaderRoute: typeof ApiCodeActivityChangesSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/drafts/confirm': {
      id: '/api/code-activity/drafts/confirm'
      path: '/api/code-activity/drafts/confirm'
      fullPath: '/api/code-activity/drafts/confirm'
      preLoaderRoute: typeof ApiCodeActivityDraftsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/github/repositories': {
      id: '/api/code-activity/github/repositories'
      path: '/api/code-activity/github/repositories'
      fullPath: '/api/code-activity/github/repositories'
      preLoaderRoute: typeof ApiCodeActivityGithubRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/act': {
      id: '/api/public/bridge/act'
      path: '/api/public/bridge/act'
      fullPath: '/api/public/bridge/act'
      preLoaderRoute: typeof ApiPublicBridgeActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/comment': {
      id: '/api/public/bridge/comment'
      path: '/api/public/bridge/comment'
      fullPath: '/api/public/bridge/comment'
      preLoaderRoute: typeof ApiPublicBridgeCommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/redeem': {
      id: '/api/public/bridge/redeem'
      path: '/api/public/bridge/redeem'
      fullPath: '/api/public/bridge/redeem'
      preLoaderRoute: typeof ApiPublicBridgeRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/thing': {
      id: '/api/public/bridge/thing'
      path: '/api/public/bridge/thing'
      fullPath: '/api/public/bridge/thing'
      preLoaderRoute: typeof ApiPublicBridgeThingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/github/authorize/callback': {
      id: '/api/code-activity/github/authorize/callback'
      path: '/api/code-activity/github/authorize/callback'
      fullPath: '/api/code-activity/github/authorize/callback'
      preLoaderRoute: typeof ApiCodeActivityGithubAuthorizeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/code-activity/github/authorize/start': {
      id: '/api/code-activity/github/authorize/start'
      path: '/api/code-activity/github/authorize/start'
      fullPath: '/api/code-activity/github/authorize/start'
      preLoaderRoute: typeof ApiCodeActivityGithubAuthorizeStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/code-activity/github/webhook': {
      id: '/api/public/code-activity/github/webhook'
      path: '/api/public/code-activity/github/webhook'
      fullPath: '/api/public/code-activity/github/webhook'
      preLoaderRoute: typeof ApiPublicCodeActivityGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BucketsRouteChildren {
  BucketsBucketIdRoute: typeof BucketsBucketIdRoute
  BucketsIndexRoute: typeof BucketsIndexRoute
}

const BucketsRouteChildren: BucketsRouteChildren = {
  BucketsBucketIdRoute: BucketsBucketIdRoute,
  BucketsIndexRoute: BucketsIndexRoute,
}

const BucketsRouteWithChildren =
  BucketsRoute._addFileChildren(BucketsRouteChildren)

interface ListsRouteChildren {
  ListsListIdRoute: typeof ListsListIdRoute
  ListsIndexRoute: typeof ListsIndexRoute
}

const ListsRouteChildren: ListsRouteChildren = {
  ListsListIdRoute: ListsListIdRoute,
  ListsIndexRoute: ListsIndexRoute,
}

const ListsRouteWithChildren = ListsRoute._addFileChildren(ListsRouteChildren)

interface TeamRouteChildren {
  TeamConversationIdRoute: typeof TeamConversationIdRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamConversationIdRoute: TeamConversationIdRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BucketsRoute: BucketsRouteWithChildren,
  ListsRoute: ListsRouteWithChildren,
  MeRoute: MeRoute,
  NudgesRoute: NudgesRoute,
  OnboardingRoute: OnboardingRoute,
  TeamRoute: TeamRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  BridgeTokenRoute: BridgeTokenRoute,
  ApiCallsRingRoute: ApiCallsRingRoute,
  ApiCodeActivityAssigneeCandidatesRoute:
    ApiCodeActivityAssigneeCandidatesRoute,
  ApiCodeActivityBranchesRoute: ApiCodeActivityBranchesRoute,
  ApiCodeActivityCapabilitiesRoute: ApiCodeActivityCapabilitiesRoute,
  ApiCodeActivityChangeStatsRoute: ApiCodeActivityChangeStatsRoute,
  ApiCodeActivityCommitDetailRoute: ApiCodeActivityCommitDetailRoute,
  ApiCodeActivityCommitsRoute: ApiCodeActivityCommitsRoute,
  ApiCodeActivityCompareRoute: ApiCodeActivityCompareRoute,
  ApiCodeActivityConnectionRoute: ApiCodeActivityConnectionRoute,
  ApiCodeActivityConsentRoute: ApiCodeActivityConsentRoute,
  ApiCodeActivityDeploymentsRoute: ApiCodeActivityDeploymentsRoute,
  ApiCodeActivityFeedRoute: ApiCodeActivityFeedRoute,
  ApiCodeActivityRefreshRoute: ApiCodeActivityRefreshRoute,
  ApiCodeActivityWorkspaceConfirmRoute: ApiCodeActivityWorkspaceConfirmRoute,
  ApiCodeActivityWorkspaceSourceRoute: ApiCodeActivityWorkspaceSourceRoute,
  ApiHubNotifyMessageRoute: ApiHubNotifyMessageRoute,
  ApiJobsCodeActivityDrainRoute: ApiJobsCodeActivityDrainRoute,
  ApiJobsDailyMaintenanceRoute: ApiJobsDailyMaintenanceRoute,
  ApiJobsEscalateNudgesRoute: ApiJobsEscalateNudgesRoute,
  ApiNudgesNotifyRoute: ApiNudgesNotifyRoute,
  ApiPushTestRoute: ApiPushTestRoute,
  ApiThingsNotifyMentionRoute: ApiThingsNotifyMentionRoute,
  ApiCodeActivityChangesDetailRoute: ApiCodeActivityChangesDetailRoute,
  ApiCodeActivityChangesDraftRoute: ApiCodeActivityChangesDraftRoute,
  ApiCodeActivityChangesSummaryRoute: ApiCodeActivityChangesSummaryRoute,
  ApiCodeActivityDraftsConfirmRoute: ApiCodeActivityDraftsConfirmRoute,
  ApiCodeActivityGithubRepositoriesRoute:
    ApiCodeActivityGithubRepositoriesRoute,
  ApiPublicBridgeActRoute: ApiPublicBridgeActRoute,
  ApiPublicBridgeCommentRoute: ApiPublicBridgeCommentRoute,
  ApiPublicBridgeRedeemRoute: ApiPublicBridgeRedeemRoute,
  ApiPublicBridgeThingRoute: ApiPublicBridgeThingRoute,
  ApiCodeActivityGithubAuthorizeCallbackRoute:
    ApiCodeActivityGithubAuthorizeCallbackRoute,
  ApiCodeActivityGithubAuthorizeStartRoute:
    ApiCodeActivityGithubAuthorizeStartRoute,
  ApiPublicCodeActivityGithubWebhookRoute:
    ApiPublicCodeActivityGithubWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
