/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BucketsRouteImport } from './routes/buckets'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as MeRouteImport } from './routes/me'
import { Route as NudgesRouteImport } from './routes/nudges'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as BridgeTokenRouteImport } from './routes/bridge.$token'
import { Route as BucketsIndexRouteImport } from './routes/buckets.index'
import { Route as BucketsBucketIdRouteImport } from './routes/buckets.$bucketId'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as ListsListIdRouteImport } from './routes/lists.$listId'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamConversationIdRouteImport } from './routes/team.$conversationId'
import { Route as ApiCallsRingRouteImport } from './routes/api/calls/ring'
import { Route as ApiHubNotifyMessageRouteImport } from './routes/api/hub/notify-message'
import { Route as ApiJobsDailyMaintenanceRouteImport } from './routes/api/jobs/daily-maintenance'
import { Route as ApiJobsEscalateNudgesRouteImport } from './routes/api/jobs/escalate-nudges'
import { Route as ApiNudgesNotifyRouteImport } from './routes/api/nudges/notify'
import { Route as ApiPublicBridgeActRouteImport } from './routes/api/public/bridge/act'
import { Route as ApiPublicBridgeCommentRouteImport } from './routes/api/public/bridge/comment'
import { Route as ApiPublicBridgeRedeemRouteImport } from './routes/api/public/bridge/redeem'
import { Route as ApiPublicBridgeThingRouteImport } from './routes/api/public/bridge/thing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsRoute = BucketsRouteImport.update({
  id: '/buckets',
  path: '/buckets',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NudgesRoute = NudgesRouteImport.update({
  id: '/nudges',
  path: '/nudges',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeTokenRoute = BridgeTokenRouteImport.update({
  id: '/bridge/$token',
  path: '/bridge/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsIndexRoute = BucketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BucketsRoute,
} as any)
const BucketsBucketIdRoute = BucketsBucketIdRouteImport.update({
  id: '/$bucketId',
  path: '/$bucketId',
  getParentRoute: () => BucketsRoute,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListsRoute,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => ListsRoute,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamConversationIdRoute = TeamConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => TeamRoute,
} as any)
const ApiCallsRingRoute = ApiCallsRingRouteImport.update({
  id: '/api/calls/ring',
  path: '/api/calls/ring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHubNotifyMessageRoute = ApiHubNotifyMessageRouteImport.update({
  id: '/api/hub/notify-message',
  path: '/api/hub/notify-message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsDailyMaintenanceRoute = ApiJobsDailyMaintenanceRouteImport.update({
  id: '/api/jobs/daily-maintenance',
  path: '/api/jobs/daily-maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsEscalateNudgesRoute = ApiJobsEscalateNudgesRouteImport.update({
  id: '/api/jobs/escalate-nudges',
  path: '/api/jobs/escalate-nudges',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNudgesNotifyRoute = ApiNudgesNotifyRouteImport.update({
  id: '/api/nudges/notify',
  path: '/api/nudges/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeActRoute = ApiPublicBridgeActRouteImport.update({
  id: '/api/public/bridge/act',
  path: '/api/public/bridge/act',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeCommentRoute = ApiPublicBridgeCommentRouteImport.update({
  id: '/api/public/bridge/comment',
  path: '/api/public/bridge/comment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeRedeemRoute = ApiPublicBridgeRedeemRouteImport.update({
  id: '/api/public/bridge/redeem',
  path: '/api/public/bridge/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeThingRoute = ApiPublicBridgeThingRouteImport.update({
  id: '/api/public/bridge/thing',
  path: '/api/public/bridge/thing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buckets': typeof BucketsRouteWithChildren
  '/lists': typeof ListsRouteWithChildren
  '/me': typeof MeRoute
  '/nudges': typeof NudgesRoute
  '/onboarding': typeof OnboardingRoute
  '/team': typeof TeamRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/bridge/$token': typeof BridgeTokenRoute
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/team/$conversationId': typeof TeamConversationIdRoute
  '/buckets/': typeof BucketsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/api/calls/ring': typeof ApiCallsRingRoute
  '/api/hub/notify-message': typeof ApiHubNotifyMessageRoute
  '/api/jobs/daily-maintenance': typeof ApiJobsDailyMaintenanceRoute
  '/api/jobs/escalate-nudges': typeof ApiJobsEscalateNudgesRoute
  '/api/nudges/notify': typeof ApiNudgesNotifyRoute
  '/api/public/bridge/act': typeof ApiPublicBridgeActRoute
  '/api/public/bridge/comment': typeof ApiPublicBridgeCommentRoute
  '/api/public/bridge/redeem': typeof ApiPublicBridgeRedeemRoute
  '/api/public/bridge/thing': typeof ApiPublicBridgeThingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/nudges': typeof NudgesRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/bridge/$token': typeof BridgeTokenRoute
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/team/$conversationId': typeof TeamConversationIdRoute
  '/buckets': typeof BucketsIndexRoute
  '/lists': typeof ListsIndexRoute
  '/team': typeof TeamIndexRoute
  '/api/calls/ring': typeof ApiCallsRingRoute
  '/api/hub/notify-message': typeof ApiHubNotifyMessageRoute
  '/api/jobs/daily-maintenance': typeof ApiJobsDailyMaintenanceRoute
  '/api/jobs/escalate-nudges': typeof ApiJobsEscalateNudgesRoute
  '/api/nudges/notify': typeof ApiNudgesNotifyRoute
  '/api/public/bridge/act': typeof ApiPublicBridgeActRoute
  '/api/public/bridge/comment': typeof ApiPublicBridgeCommentRoute
  '/api/public/bridge/redeem': typeof ApiPublicBridgeRedeemRoute
  '/api/public/bridge/thing': typeof ApiPublicBridgeThingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buckets': typeof BucketsRouteWithChildren
  '/lists': typeof ListsRouteWithChildren
  '/me': typeof MeRoute
  '/nudges': typeof NudgesRoute
  '/onboarding': typeof OnboardingRoute
  '/team': typeof TeamRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/bridge/$token': typeof BridgeTokenRoute
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/team/$conversationId': typeof TeamConversationIdRoute
  '/buckets/': typeof BucketsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/api/calls/ring': typeof ApiCallsRingRoute
  '/api/hub/notify-message': typeof ApiHubNotifyMessageRoute
  '/api/jobs/daily-maintenance': typeof ApiJobsDailyMaintenanceRoute
  '/api/jobs/escalate-nudges': typeof ApiJobsEscalateNudgesRoute
  '/api/nudges/notify': typeof ApiNudgesNotifyRoute
  '/api/public/bridge/act': typeof ApiPublicBridgeActRoute
  '/api/public/bridge/comment': typeof ApiPublicBridgeCommentRoute
  '/api/public/bridge/redeem': typeof ApiPublicBridgeRedeemRoute
  '/api/public/bridge/thing': typeof ApiPublicBridgeThingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buckets'
    | '/lists'
    | '/me'
    | '/nudges'
    | '/onboarding'
    | '/team'
    | '/welcome'
    | '/bridge/$token'
    | '/buckets/$bucketId'
    | '/lists/$listId'
    | '/team/$conversationId'
    | '/buckets/'
    | '/lists/'
    | '/team/'
    | '/api/calls/ring'
    | '/api/hub/notify-message'
    | '/api/jobs/daily-maintenance'
    | '/api/jobs/escalate-nudges'
    | '/api/nudges/notify'
    | '/api/public/bridge/act'
    | '/api/public/bridge/comment'
    | '/api/public/bridge/redeem'
    | '/api/public/bridge/thing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/me'
    | '/nudges'
    | '/onboarding'
    | '/welcome'
    | '/bridge/$token'
    | '/buckets/$bucketId'
    | '/lists/$listId'
    | '/team/$conversationId'
    | '/buckets'
    | '/lists'
    | '/team'
    | '/api/calls/ring'
    | '/api/hub/notify-message'
    | '/api/jobs/daily-maintenance'
    | '/api/jobs/escalate-nudges'
    | '/api/nudges/notify'
    | '/api/public/bridge/act'
    | '/api/public/bridge/comment'
    | '/api/public/bridge/redeem'
    | '/api/public/bridge/thing'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buckets'
    | '/lists'
    | '/me'
    | '/nudges'
    | '/onboarding'
    | '/team'
    | '/welcome'
    | '/bridge/$token'
    | '/buckets/$bucketId'
    | '/lists/$listId'
    | '/team/$conversationId'
    | '/buckets/'
    | '/lists/'
    | '/team/'
    | '/api/calls/ring'
    | '/api/hub/notify-message'
    | '/api/jobs/daily-maintenance'
    | '/api/jobs/escalate-nudges'
    | '/api/nudges/notify'
    | '/api/public/bridge/act'
    | '/api/public/bridge/comment'
    | '/api/public/bridge/redeem'
    | '/api/public/bridge/thing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BucketsRoute: typeof BucketsRouteWithChildren
  ListsRoute: typeof ListsRouteWithChildren
  MeRoute: typeof MeRoute
  NudgesRoute: typeof NudgesRoute
  OnboardingRoute: typeof OnboardingRoute
  TeamRoute: typeof TeamRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  BridgeTokenRoute: typeof BridgeTokenRoute
  ApiCallsRingRoute: typeof ApiCallsRingRoute
  ApiHubNotifyMessageRoute: typeof ApiHubNotifyMessageRoute
  ApiJobsDailyMaintenanceRoute: typeof ApiJobsDailyMaintenanceRoute
  ApiJobsEscalateNudgesRoute: typeof ApiJobsEscalateNudgesRoute
  ApiNudgesNotifyRoute: typeof ApiNudgesNotifyRoute
  ApiPublicBridgeActRoute: typeof ApiPublicBridgeActRoute
  ApiPublicBridgeCommentRoute: typeof ApiPublicBridgeCommentRoute
  ApiPublicBridgeRedeemRoute: typeof ApiPublicBridgeRedeemRoute
  ApiPublicBridgeThingRoute: typeof ApiPublicBridgeThingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets': {
      id: '/buckets'
      path: '/buckets'
      fullPath: '/buckets'
      preLoaderRoute: typeof BucketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nudges': {
      id: '/nudges'
      path: '/nudges'
      fullPath: '/nudges'
      preLoaderRoute: typeof NudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge/$token': {
      id: '/bridge/$token'
      path: '/bridge/$token'
      fullPath: '/bridge/$token'
      preLoaderRoute: typeof BridgeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/': {
      id: '/buckets/'
      path: '/'
      fullPath: '/buckets/'
      preLoaderRoute: typeof BucketsIndexRouteImport
      parentRoute: typeof BucketsRoute
    }
    '/buckets/$bucketId': {
      id: '/buckets/$bucketId'
      path: '/$bucketId'
      fullPath: '/buckets/$bucketId'
      preLoaderRoute: typeof BucketsBucketIdRouteImport
      parentRoute: typeof BucketsRoute
    }
    '/lists/': {
      id: '/lists/'
      path: '/'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof ListsRoute
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof ListsRoute
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/$conversationId': {
      id: '/team/$conversationId'
      path: '/$conversationId'
      fullPath: '/team/$conversationId'
      preLoaderRoute: typeof TeamConversationIdRouteImport
      parentRoute: typeof TeamRoute
    }
    '/api/calls/ring': {
      id: '/api/calls/ring'
      path: '/api/calls/ring'
      fullPath: '/api/calls/ring'
      preLoaderRoute: typeof ApiCallsRingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hub/notify-message': {
      id: '/api/hub/notify-message'
      path: '/api/hub/notify-message'
      fullPath: '/api/hub/notify-message'
      preLoaderRoute: typeof ApiHubNotifyMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/daily-maintenance': {
      id: '/api/jobs/daily-maintenance'
      path: '/api/jobs/daily-maintenance'
      fullPath: '/api/jobs/daily-maintenance'
      preLoaderRoute: typeof ApiJobsDailyMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/escalate-nudges': {
      id: '/api/jobs/escalate-nudges'
      path: '/api/jobs/escalate-nudges'
      fullPath: '/api/jobs/escalate-nudges'
      preLoaderRoute: typeof ApiJobsEscalateNudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nudges/notify': {
      id: '/api/nudges/notify'
      path: '/api/nudges/notify'
      fullPath: '/api/nudges/notify'
      preLoaderRoute: typeof ApiNudgesNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/act': {
      id: '/api/public/bridge/act'
      path: '/api/public/bridge/act'
      fullPath: '/api/public/bridge/act'
      preLoaderRoute: typeof ApiPublicBridgeActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/comment': {
      id: '/api/public/bridge/comment'
      path: '/api/public/bridge/comment'
      fullPath: '/api/public/bridge/comment'
      preLoaderRoute: typeof ApiPublicBridgeCommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/redeem': {
      id: '/api/public/bridge/redeem'
      path: '/api/public/bridge/redeem'
      fullPath: '/api/public/bridge/redeem'
      preLoaderRoute: typeof ApiPublicBridgeRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/thing': {
      id: '/api/public/bridge/thing'
      path: '/api/public/bridge/thing'
      fullPath: '/api/public/bridge/thing'
      preLoaderRoute: typeof ApiPublicBridgeThingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BucketsRouteChildren {
  BucketsBucketIdRoute: typeof BucketsBucketIdRoute
  BucketsIndexRoute: typeof BucketsIndexRoute
}

const BucketsRouteChildren: BucketsRouteChildren = {
  BucketsBucketIdRoute: BucketsBucketIdRoute,
  BucketsIndexRoute: BucketsIndexRoute,
}

const BucketsRouteWithChildren =
  BucketsRoute._addFileChildren(BucketsRouteChildren)

interface ListsRouteChildren {
  ListsListIdRoute: typeof ListsListIdRoute
  ListsIndexRoute: typeof ListsIndexRoute
}

const ListsRouteChildren: ListsRouteChildren = {
  ListsListIdRoute: ListsListIdRoute,
  ListsIndexRoute: ListsIndexRoute,
}

const ListsRouteWithChildren = ListsRoute._addFileChildren(ListsRouteChildren)

interface TeamRouteChildren {
  TeamConversationIdRoute: typeof TeamConversationIdRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamConversationIdRoute: TeamConversationIdRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BucketsRoute: BucketsRouteWithChildren,
  ListsRoute: ListsRouteWithChildren,
  MeRoute: MeRoute,
  NudgesRoute: NudgesRoute,
  OnboardingRoute: OnboardingRoute,
  TeamRoute: TeamRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  BridgeTokenRoute: BridgeTokenRoute,
  ApiCallsRingRoute: ApiCallsRingRoute,
  ApiHubNotifyMessageRoute: ApiHubNotifyMessageRoute,
  ApiJobsDailyMaintenanceRoute: ApiJobsDailyMaintenanceRoute,
  ApiJobsEscalateNudgesRoute: ApiJobsEscalateNudgesRoute,
  ApiNudgesNotifyRoute: ApiNudgesNotifyRoute,
  ApiPublicBridgeActRoute: ApiPublicBridgeActRoute,
  ApiPublicBridgeCommentRoute: ApiPublicBridgeCommentRoute,
  ApiPublicBridgeRedeemRoute: ApiPublicBridgeRedeemRoute,
  ApiPublicBridgeThingRoute: ApiPublicBridgeThingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
